version: 0.2

env:
  variables:
    TEST_ENV_VARIABLE: prodArtifacts
phases:
  build:
    commands:
      - sbt clean compile dist
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  base-directory: 'target/universal'
  files:
    - '**/*.zip'