version: 0.2

env:
  variables:
    TEST_ENV_VARIABLE: prodArtifacts
phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - java -version
      - apt-get update
      - apt-get -qq -y install wget curl unzip zip gnupg
      - echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
      - curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add
      - apt-get update
      - apt-get install sbt -y
  build:
    commands:
      - sbt clean compile dist
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  base-directory: 'target/universal'
  files:
    - '**/*.zip'